on:
  push:
    branches:
      - milaner
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run composer install
        run: composer install --no-dev --optimize-autoloader --no-progress

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete --exclude .htaccess --exclude config.php
          path: /
          remote_path: /var/www/virtual/${{ secrets.UBERSPACE_USER }}/html
          remote_host: ${{ secrets.UBERSPACE_HOST }}
          remote_user: ${{ secrets.UBERSPACE_USER }}
          remote_key: ${{ secrets.UBERSPACE_DEPLOY_KEY }}
